### ISSUE TITLE
[OPMERKING]

### ISSUE THREAD

**Issue by paulvangent** [Logius-standaarden/OIN-Stelsel#1]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bij OIN en HRN: wordt de vraag gesteld waar het HRN wordt bijgehouden?
Bij nieuwe voorstellen 2020: het BRI/n wodt ook teogevoegd?
Bij Context Centrale OIN Raadpleegvoorziening (COR): UZI toevoegen? (of is dit een register als voorbeeld, brin wordt wel genoemd), DK standaard links boven (wie is verantwoordelijk-> Logius), pijl van DK standaard naar voorwaarden DK, nog toevoegen gr codes (KOOP) en eventueel gs codes,  evnetueel benoemen CPA register/comopliance voorziening/certificaten? -> verbinden met dk standaard?, 
Bij Voor wie is het OIN: typo 1e bullet: of college, 2e en 3e bullet ; teveel, GBA =  BRP?

Bij Op welke manier kan een organisatie een OIN verkrijgen: bracket teveel bij de link. 
Bij De relatie tussen SubOINs en de verantwoordelijke rechtspersoon kan in de COR worden vastgelegd en wordt publiekelijk getoond bij raadpleging van de voorziening. -> alleen te zien in de API niet in de browser. 
Typo's: Niet alleen actieve Oins en SubOINss 
Private partijen kunnen ten behoeve van (SAAS-)dienstverlening aan hun publieke klanten SubOINs aanvragen -> voor ipv aan? 
Naast Gemeentecode kan een vertaling worden opgevraagd naar Provincie-, Waterschap- of Ministeriecode-> + GR code?
Bij Rollen in het OIN stelsel: kan als geheel gekopieerd worden uit andere document?

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PieterHering** [comment]
Dank voor de feedback! Ik heb de vragen zoveel mogelijk verwerkt

- [x] Bij OIN en HRN: wordt de vraag gesteld waar het HRN wordt bijgehouden?

> Toegevoegd in de paragraaf "Op welke manier kan een organisatie een OIN verkrijgen" bij punt 2 


- [x] Bij nieuwe voorstellen 2020: het BRIN wordt ook teogevoegd?
> Is nog niet opgepakt. De behoefte van de onderwijssector is er wel.
    
- [ ] Bij Context Centrale OIN Raadpleegvoorziening (COR): UZI toevoegen? (of is dit een register als voorbeeld, brin wordt wel genoemd)
> Niet aangepast. Het is een voorbeeld. Het gaat om het idee.

- [ ] DK standaard links boven (wie is verantwoordelijk-> Logius), pijl van DK standaard naar voorwaarden DK, nog toevoegen gr codes (KOOP) en eventueel gs codes, evnetueel benoemen CPA register/comopliance voorziening/certificaten? -> verbinden met dk standaard?,
> Niet aangepast. We willen in het context diagram de focus op het OIN houden.


- [x] Bij Voor wie is het OIN: typo 1e bullet: of college, 2e en 3e bullet ; teveel, GBA = BRP?
> typo's aangepast. De Algemene Logius Voorwaarden gebruikt de term GBA. Die kunnen wij niet wijzigen 

- [x] Bij Op welke manier kan een organisatie een OIN verkrijgen: bracket teveel bij de link.
> aangepast

- [x] Bij De relatie tussen SubOINs en de verantwoordelijke rechtspersoon kan in de COR worden vastgelegd en wordt publiekelijk getoond bij raadpleging van de voorziening. -> alleen te zien in de API niet in de browser.
> aangepast

- [x] Typo's: Niet alleen actieve Oins en SubOINss
> aangepast

- [x] Private partijen kunnen ten behoeve van (SAAS-)dienstverlening aan hun publieke klanten SubOINs aanvragen -> voor ipv aan?
> aangepast

- [x] Naast Gemeentecode kan een vertaling worden opgevraagd naar Provincie-, Waterschap- of Ministeriecode-> + GR code?
> Wist niet welke status dit heeft. Zitten de GR's alin de COR?

- [ ] Bij Rollen in het OIN stelsel: kan als geheel gekopieerd worden uit andere document?
> Ik begrijp deze vraag niet. Kan je deze verduidelijken?
