### ISSUE TITLE
url aanpassing in het document

### ISSUE THREAD

**Issue by eark00001** [Logius-standaarden/OIN-Stelsel#17]
### Soort

- [ ] Tekstuele fout
- [X] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

In het OIN-stelsel document wordt verwezen naar de url https://portaal.digikoppeling.nl , deze url is vervangen door https://oinregister.logius.nl

Deze verwijzing komt acht maal voor.

### Naam

Ed van der Ark

### Email

ed.vander.ark@logius.nl

### Organisatie

Logius

**Comment by sanderke** [comment]
Bedankt. De URL's zijn aangepast.
