### ISSUE TITLE
[OPMERKING]

### ISSUE THREAD

**Issue by paulvangent** [Logius-standaarden/OIN-Stelsel#2]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Voldoet aan de eisen die gesteld worden door de beheerders van overheidsregisters. -> welke eisen zijn dit?
De COR API is publiek beschikbaar voor systemen. De beheerder van de COR kan de toegang reguleren, bijvoorbeeld door het verstrekken van zogenaamde API-keys, of door gebruik te maken van tweezijdig TLS. -> API keys nog niet en geen tweezijdig TLS
bij Kwaliteitsborging: hebben wij als beheerder niet meer verantwoordelijkheid?
bij Samenwerkingsverbanden Een deelnemer binnen een (publiek) samenwerkingsverband zonder rechtspersoonlijkheid mag een OIN uitgeven aan het samenwerkingsverband, mits de betreffende deelnemer OIN-houder-> moet zijn sub-OIN?
De OIN–houder moet alle mutaties met betrekking tot de SubOINs doorgeven aan Logius, beheerder van de COR.-> is nog niet ingeregeld?
SubOINs: geldigheidsduur en bewaartermijnen: goed controleren of we hier al invulling aan geven. 
SubOINs: samenstelling en raadpleging: kop slaat niet opde tekst daaronder die alleen over OIN's gaat?
De relatie is alleen te raadplegen via de COR. Een SubOIN is een OIN voor entiteiten zonder rechtspersoonlijkheid, zoals een organisatie die niet is ingeschreven in het Handelsregister, een organisatie-onderdeel of een voorziening. -> alleen via API. Hele alinea moet zijn sub-OIN?

Schets van de COR: nr's in de tabel kloppen niet

Bijlage b: links staan met ]

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PieterHering** [comment]
Dank voor de feedback! We hebben de vragen zoveel mogelijk verwerkt

- [x] Voldoet aan de eisen die gesteld worden door de beheerders van overheidsregisters. -> welke eisen zijn dit? 
> Deze zin is vooralsnog verwijderd. Het was niet meer te achterhalen welke eisen dit zijn. Als hierover meer informatie beschikbaar is, zullen we dit weer herstellen en met de beheerder van de COR afstemmen. 

- [x]  De COR API is publiek beschikbaar voor systemen. De beheerder van de COR kan de toegang reguleren, bijvoorbeeld door het verstrekken van zogenaamde API-keys, of door gebruik te maken van tweezijdig TLS. -> API keys nog niet en geen tweezijdig TLS
> deze zin is gehandhaafd. Er staat 'kan' en niet 'zal' of 'reguleert de toegang'. Mocht er een aanleiding voor zijn, dan kan de COR een vorm van regulatie toepassen, bijvoorbeeld via  API-keys.

- [x] bij Kwaliteitsborging: hebben wij als beheerder niet meer verantwoordelijkheid?

> Ik heb de paragraaf zoveel mogelijk in lijn gebracht met de Voorwaarden Digikoppeling.  

OIN-Houder en SubOIN-Beheerder
> Getriggerd door de vragen hebben we op een aantal plekken het woord OIN-houder vervangen door SUbOIN-beheerder

- [x] bij Samenwerkingsverbanden Een deelnemer binnen een (publiek) samenwerkingsverband zonder rechtspersoonlijkheid mag een OIN uitgeven aan het samenwerkingsverband, mits de betreffende deelnemer OIN-houder-> moet zijn sub-OIN?
> zin aangepast 

- [x] SubOINs: samenstelling en raadpleging: kop slaat niet op de tekst daaronder die alleen over OIN's gaat?

>  paragraaf verwijderd

- [x] De relatie is alleen te raadplegen via de COR. Een SubOIN is een OIN voor entiteiten zonder rechtspersoonlijkheid, zoals een organisatie die niet is ingeschreven in het Handelsregister, een organisatie-onderdeel of een voorziening. -> alleen via API. 
> check. aangepast

Hele alinea moet zijn sub-OIN?
> Goed punt. Tekst is aangepast

- [x] Schets van de COR: nr's in de tabel kloppen niet
> aangepast 

- [x] Bijlage b: links staan met ]
> aangepast
