### ISSUE TITLE
RSIN of Kvk nummer leidend voor OIN?

### ISSUE THREAD

**Issue by logius-standaardenbeheer** [Logius-standaarden/OIN-Stelsel#5]
Wanneer een organisatie over een kvk nummer beschikt dient dit nummer als basis te worden genomen voor het OIN (en niet het RSIN).
Wens is dit meer expliciet als regel in het OIN beleid op te nemen. Besproken met Interfaces team.

**Comment by edwinwisse** [comment]
In sectie [Identiteit en nummer in _Digikoppeling Identificatie en Authenticatie_](https://logius-standaarden.github.io/Digikoppeling-Identificatie-en-Authenticatie/#identiteit-en-nummer) wordt gesteld dat het RSIN het meest geschikt is als identificerend nummer en dat het KvK nummer (naar alle waarschijnlijkheid) *niet* geschikt is als basis voor een OIN nummer voor overheden, maar *wel* voor bedrijven en instellingen.
In dit document staat ook een [voorstel](https://logius-standaarden.github.io/Digikoppeling-Identificatie-en-Authenticatie/#voorstel): (gebruik) "...het RSIN voor de grote groep organisaties waarvoor dat RSINr bestaat en gebruikt kan worden". Hierbij wordt _geen_ voorbehoud gemaakt voor bedrijven.
In het verleden zijn KvK nummers gebruikt voor bedrijven en RSINs voor overheden. Dat wijkt af van het voorstel. Volgens het voorstel zou een RSIN toegepast moeten worden waar nodig.
Het is wel nodig om de formulering in  [_Digikoppeling Identificatie en Authenticatie_](https://logius-standaarden.github.io/Digikoppeling-Identificatie-en-Authenticatie/) expliciet te maken zodat eenduidig is waar het OIN op wordt gebaseerd.

**Comment by wisze** [comment]
In het [Digikoppeling Identificatie en Authenticatie document](https://github.com/Logius-standaarden/Digikoppeling-Identificatie-en-Authenticatie) staat zelfs dat een OIN aangepast moet worden als een RSIN nummer beschikbaar komt voor een organisatie die nog een OIN had wat _niet_ op een RSIN gebaseerd was. 
Dat heeft impact op de implementatie en stel een extra eis aan het OIN registerbeheer.

**Comment by edwinwisse** [comment]
Volgens KvK documentatie kan een RSIN opgevraagd worden via de API: https://developers.kvk.nl/nl/apis/basisprofiel

**Comment by edwinwisse** [comment]
Intern overleg Logius 14/9/2023:
- Veel nummers zijn al gebaseerd op KvK nummers
- Er komen weinig overheden bij die een nieuw nummer nodig hebben dus de meeste nieuwe aanvragers zijn private partijen
- Private partijen kunnen een HRM gebruiken wat overeenkomt met het OIN, gebaseerd op hun Kvk nummer. Deze nummers komen *niet* in het OIN register maar zijn wel geldige (HRN) identificatienummers.

Dus: om verwarring te voorkomen stelt Logius voor in de documentatie op te nemen dat **een OIN gebaseerd wordt op een KvK nummer. Alleen als een (overheids)partij geen KvK nummer heeft wordt het OIN gebaseerd op het RSIN**. Documentatie wordt aangepast: De [OIN stelsel beschrijving](https://logius-standaarden.github.io/OIN-Stelsel/) en [Digikoppeling Identificatie en Authenticatie](https://logius-standaarden.github.io/Digikoppeling-Identificatie-en-Authenticatie/)
