### ISSUE TITLE
OrganisatieType is niet gedefinieerd

### ISSUE THREAD

**Issue by ThiesMesdag** [Logius-standaarden/OIN-Stelsel#9]
In de download van de actuele OIN's zit een veld Organisatie Type. Dit veld is nergens beschreven in de documentatie (behalve dat het wordt genoemd in een voorbeeld bericht). 

In de download komen de volgende waarden voor (met hun vermoedelijke betekenis):
* GM - Gemeente 
* GR - Gemeenschappelijke regeling
* MNRE - Ministerie
* PV - Provincie
* WS - Waterschap

**Comment by sanderke** [comment]
Bedankt voor de melding. Dit punt wordt opgenomen in de komende verbetering van de documentatie op deze pagina:
https://portaal.digikoppeling.nl/registers/corApi/index

Vervolgens zal een duidelijkere verwijzing naar deze pagina opgenomen worden in het document "OIN Stelsel".

**Comment by ThiesMesdag** [comment]
Ik zou ook een toevoeging in https://publicatie.centrumvoorstandaarden.nl/dk/oin/ verwachten.

**Comment by sanderke** [comment]
> Ik zou ook een toevoeging in https://publicatie.centrumvoorstandaarden.nl/dk/oin/ verwachten.

De nieuwe versie van het document "OIN Stelsel" zal daar verschijnen.

**Comment by sanderke** [comment]
De pagina ["Doel en gebruik van de COR API"](https://portaal.digikoppeling.nl/registers/corApi/index) is bijgewerkt met verdere toelichting over `OrganisatieType` en er wordt nu duidelijker naar verwezen in het document ["OIN Stelsel"](https://publicatie.centrumvoorstandaarden.nl/dk/oin/#cor-api).
